# Generated by Django 5.2.7 on 2025-11-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300)),
                ('registry', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'associate',
                'constraints': [models.UniqueConstraint(fields=('fullname', 'registry'), name='unique_fullname_registry')],
            },
        ),
    ]
